export const mockedCardData = [
  {
    id: 1,
    title: "Card Title 1",
    content: "Content for card 1 Content for card 1 ",
    url: "https://www.google.com",
  },
  {
    id: 2,
    title: "Card Title 2",
    content: "Content for card 2",
    url: "https://www.amazon.com",
  },
  {
    id: 3,
    title: "Card Title 3",
    content: "Content for card 3",
    url: "https://www.facebook.com",
  },
  {
    id: 4,
    title: "Card Title 4",
    content: "Content for card 4",
    url: "https://www.twitter.com",
  },
  {
    id: 5,
    title: "Card Title 5",
    content: "Content for card 5",
    url: "https://www.linkedin.com",
  },
  {
    id: 6,
    title: "Card Title 6",
    content: "Content for card 6",
    url: "https://www.github.com",
  },
  {
    id: 7,
    title: "Card Title 7",
    content: "Content for card 7",
    url: "https://www.google.com",
  },
  {
    id: 8,
    title: "Card Title 8",
    content: "Content for card 8",
    url: "https://www.amazon.com",
  },
  {
    id: 9,
    title: "Card Title 9",
    content: "Content for card 9",
    url: "https://www.facebook.com",
  },
  {
    id: 10,
    title: "Card Title 10",
    content: "Content for card 10",
    url: "https://www.twitter.com",
  },
  {
    id: 11,
    title: "Card Title 11",
    content: "Content for card 11",
    url: "https://www.linkedin.com",
  },
  {
    id: 12,
    title: "Card Title 12",
    content: "Content for card 12",
    url: "https://www.github.com",
  },
  {
    id: 13,
    title: "Card Title 13",
    content: "Content for card 13",
    url: "https://www.microsoft.com",
  },
  {
    id: 14,
    title: "Card Title 14",
    content: "Content for card 14",
    url: "https://www.apple.com",
  },
  {
    id: 15,
    title: "Card Title 15",
    content: "Content for card 15",
    url: "https://www.netflix.com",
  },
  {
    id: 16,
    title: "Card Title 16",
    content: "Content for card 16",
    url: "https://www.spotify.com",
  },
  {
    id: 17,
    title: "Card Title 17",
    content: "Content for card 17",
    url: "https://www.reddit.com",
  },
  {
    id: 18,
    title: "Card Title 18",
    content: "Content for card 18",
    url: "https://www.quora.com",
  },
  {
    id: 19,
    title: "Card Title 19",
    content: "Content for card 19",
    url: "https://www.wikipedia.org",
  },
  {
    id: 20,
    title: "Card Title 20",
    content: "Content for card 20",
    url: "https://www.youtube.com",
  },
  {
    id: 21,
    title: "Card Title 21",
    content: "Content for card 21",
    url: "https://www.instagram.com",
  },
  {
    id: 22,
    title: "Card Title 22",
    content: "Content for card 22",
    url: "https://www.tiktok.com",
  },
];
